name: Make Device Tree

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cpio android-sdk-libsparse-utils p7zip-full
          pip install twrpdtgen gdown

      - name: Download Images from Google Drive
        run: |
          # Скачиваем vendor_boot
          gdown "https://drive.google.com/uc?id=1BFML1FevkxGUDiI3I2ha6qCAvNOC-aO7" -O vendor_boot.img
          # Скачиваем boot (вставьте ID от boot.img)
          gdown "https://drive.google.com/uc?id=ВСТАВЬТЕ_ID_BOOT_IMG" -O boot.img

      - name: Generate Device Tree
        run: |
          mkdir output
          # Скармливаем boot.img вместе с vendor_boot.img, чтобы вытащить build.prop
          python3 -m twrpdtgen boot.img vendor_boot.img -o output/

      - name: Upload Device Tree Artifact
        uses: actions/upload-artifact@v4
        with:
          name: device-tree
          path: output/
